<?php
// get_games.php - Secure game data endpoint
session_start();

// ================= SECURITY CHECK =================
// Check if user is authenticated via PIN
if (!isset($_SESSION['pin_verified']) || $_SESSION['pin_verified'] !== true) {
    header('Content-Type: application/json');
    http_response_code(403); // Forbidden
    echo json_encode([
        'success' => false,
        'error' => 'Access denied. Please verify PIN first.',
        'redirect' => 'index.html'
    ]);
    exit;
}

// Check token expiry (24 hours)
if (isset($_SESSION['verified_time']) && (time() - $_SESSION['verified_time']) > (24 * 60 * 60)) {
    session_destroy();
    header('Content-Type: application/json');
    echo json_encode([
        'success' => false,
        'error' => 'Session expired. Please verify PIN again.',
        'redirect' => 'index.html'
    ]);
    exit;
}

// ================= GAME DATA =================
$gamesData = [
    [
        'id' => 'cod-mw2',
        'name' => 'COD MW2',
        'image' => 'https://i.postimg.cc/RhJbSY2f/Picsart-25-12-17-23-43-31-792.jpg',
        'category' => 'android',
        'size' => '7.19 GB',
        'description' => 'Game hii ni kali sana na ina maudhui ya Kivita mwanzo mwisho hakuna kupoa na kila Misheni vinaibuka vikwazo vipya kiufupi hii game ni kali !',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://romsfun.com/roms/playstation-3/call-of-duty-modern-warfare-2.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/RPCSX/rpcsx-ui-android/releases/tag/v20250425'),
        'graphicsLink' => base64_encode('https://github.com/K11MCH1/AdrenoToolsDrivers/releases'),
        'firmwareLink' => base64_encode('https://www.techspot.com/drivers/driver/file/information/17026/'),
        'videoLink' => base64_encode('https://www.youtube.com/watch?v=YOUR_VIDEO_ID'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9.0+', 'RAM 4GB+']
    ],
    [
        'id' => 'pes-2026',
        'name' => 'PES 2026',
        'image' => 'https://i.postimg.cc/SxPNJz5b/efootball-5c-3840x2400.jpg',
        'category' => 'android',
        'size' => '1.15 GB',
        'description' => 'Ufikirie ukiwa kwenye uwanja wenye jukwaa linalovuma, unapiga pasi ya kusisimua na kufunga goli la kushangaza. Hapa ndio ulimwengu wako wa soka, wewe ndio nyota!',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/s57ae54sfhh7va7/BETEGAMING_EFOOTBALL_2026_PSP_ISO.rar/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'saveDataLink' => base64_encode('https://www.mediafire.com/file/se6d8fcs5sp3jcg/EFOOTBALL_2026_PSP_TEXTURES_%252B_SAVEDATA_BETEGAMING.rar/file'),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('https://www.youtube.com/watch?v=YOUR_VIDEO_ID'),
        'version' => 'null',
        'ram' => '3GB+',
        'requirements' => ['Android 9+', 'RAM 3GB+']
    ],
    [
        'id' => 'blur',
        'name' => 'BLUR',
        'image' => 'https://i.postimg.cc/T1L2f22G/wp12417971-blur-racing-wallpapers.jpg',
        'category' => 'android',
        'size' => '5.15 GB',
        'description' => 'Hisia ya kukimbiza gari lako kwenye barabara zenye mvurugiko, na kila kona inakupa raha ya kutosha. Ufikirie kama kuwa ndani ya filamu ya harakati, lakini wewe ndio dereva!',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/t6ozu1mjs75zkin/Blur_Win_R_EN.zip/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://www.mediafire.com/file/yrfj0gv2n79szhn/GameHub_5.3.2_3bd6c76401a1a05e60854cc760be65b7.apk/file'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('https://t.me/wolftz'),
        'version' => 'null',
        'ram' => '3GB+',
        'requirements' => ['Android 10+', 'RAM 4GB+']
    ],
    [
        'id' => 'gta-v',
        'name' => 'GTA V',
        'image' => 'https://i.postimg.cc/3NCSymx3/wp6133812-gta-v-desktop-wallpapers.jpg',
        'category' => 'android',
        'size' => '10.2 GB',
        'description' => 'Hii no Grand theft gta V ambayo inacheza kwenye Simu bila shida wala tatizo kwa High perfomnce. game Hii ni Special kwa 30fps yaani simu zenye uwezo mdogo pia game hii ni Offline \n\n Zip password: GTATONY YT 10GB',
        'keyLink' => base64_encode(''),
        'gameLink' => base64_encode('https://gofile.io/d/eeoLh7'),
        'driversLink' => base64_encode('https://www.mediafire.com/file/nxg7vrlw3jp4ozp/GTA_5_IMP_FILES_BY_GTASATONY.7z/file'),
        'emulatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi/releases'),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('https://vimeo.com/1149915959'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'justcause-ii',
        'name' => 'JUST CAUSE II',
        'image' => 'https://i.postimg.cc/52BBBwd7/Picsart-25-12-22-02-48-58-236.jpg',
        'category' => 'android',
        'size' => '4.1 GB',
        'description' => 'Fikiri unaruka kutoka ndege bila parachuti, ukishika bunduki na kulipua kila kitu mbele yako. Bonge ya Game kuwahi kutokea pia ina graphics kali sana',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://buzzheavier.com/wd40jnidba2j'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://www.mediafire.com/file/yrfj0gv2n79szhn/GameHub_5.3.2_3bd6c76401a1a05e60854cc760be65b7.apk/file'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 8+', 'RAM 4GB+']
    ],
    [
        'id' => 'cod-black-ops-6',
        'name' => 'COD BLACK OPS 6',
        'image' => 'https://i.postimg.cc/wjMKY06p/Picsart-25-12-17-18-31-31-375.jpg',
        'category' => 'cloud',
        'size' => 'Null',
        'description' => 'Game hii ni kali sana na ina maudhui ya Kivita mwanzo mwisho hakuna kupoa na kila Misheni vinaibuka vikwazo vipya kiufupi hii game ni kali, Graphics ya Hii game ni 4K',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 8.0+', 'RAM 4GB+']
    ],
    [
        'id' => 'amazing-spiderman',
        'name' => 'AMAZING SPIDERMAN',
        'image' => 'https://i.postimg.cc/dt37DBxd/Picsart-25-12-17-22-32-42-142.jpg',
        'category' => 'android',
        'size' => '10.8 GB',
        'description' => 'Tembea angani ukiwa kama Peter Parker halisi, ukihama kati ya majengo makubwa ya New York. Hapa ndio unapojisikia kama shujaa, huku ukipambana na Villains wanaosumbua mji',
        'keyLink' => base64_encode('https://prodkeys.net/cemu-keys/'),
        'gameLink' => base64_encode('https://romspure.cc/roms/nintendo-wii-u/the-amazing-spider-man-6/'),
        'yuzuLink' => base64_encode('#'),
        'cemuLink' => base64_encode('https://cemu.en.uptodown.com/android'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 10+', 'RAM 4GB+']
    ],
    [
        'id' => 'bright-memory',
        'name' => 'BRIGHT MEMORY',
        'image' => 'https://i.postimg.cc/VNjBKFwf/Picsart-25-12-19-13-54-04-278.jpg',
        'category' => 'android',
        'size' => '2.14 GB',
        'description' => 'Game hii ni kali sana na ina maudhui ya Kivita mwanzo mwisho hakuna kupoa na kila Misheni vinaibuka vikwazo vipya kiufupi hii game ni kali,Graphics ya Hii game ni 4K',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://5play.org/en/20091-bright-memory-infinite.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'gta-vice-city',
        'name' => 'GTA VICE CITY',
        'image' => 'https://i.postimg.cc/wvTz09ZW/Picsart-25-12-17-23-11-59-195.jpg',
        'category' => 'android',
        'size' => '3.48 GB',
        'description' => 'Rudi kwenye enzi za miaka ya 80, ulimwengu wa muziki mzuri na gari zenye rangi kali.Game hii ni Kali na inacheza kwenye Simu yako',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/qxsb5l2tb7ivb0s/GTA-Vice-City-Definitiveeee-60-FPS-v1.90.0-mod-apkvision.apk/file?fbclid=I'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '3GB+',
        'requirements' => ['Windows 7+', 'RAM 3GB+']
    ],
    [
        'id' => 'far-cry3',
        'name' => 'FAR CRY 3',
        'image' => 'https://i.postimg.cc/QCfkrdn8/IMG-20251217-214840-174.jpg',
        'category' => 'android',
        'size' => '7.6 GB',
        'description' => 'Jiokoe kutoka kwenye kisiwa cha wahalifu,kutana na bandits wa misituni na utapambana nao wote Utawakalisha.Hapa ndio unapojifunza kuishi kwa nguvu zako zote ili kusurvive Vikwazo.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://buzzheavier.com/hnam4zxjo3k5'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://www.mediafire.com/file_premium/zhlgv398z1ksy24/GameHub-Lite-v5.1.3.apk/file'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 10', 'RAM 6GB+']
    ],
    [
        'id' => 'euro-truck',
        'name' => 'EURO TRUCK',
        'image' => 'https://i.postimg.cc/j24jC8Vq/Picsart-25-12-17-22-55-11-735.jpg',
        'category' => 'android',
        'size' => '3.51 GB',
        'description' => 'Panda kwenye lori yako na usafiri hadi nchi za Ulaya, ukifurahia mandhari ya kupendeza. Hii si kazi tu, ni safari ya kutuliza roho! pia game ina Quality ya hali ya Juu',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/l4dhn8d1a4gug1g/ETS2_1.36.2.2_%252B_70_DLC_%2528_Road_To_Black_Sea_DLC%2529_BY_SA.zip/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://www.mediafire.com/file/yrfj0gv2n79szhn/GameHub_5.3.2_3bd6c76401a1a05e60854cc760be65b7.apk/file'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 8+', 'RAM 4GB+']
    ],
    [
        'id' => 'tomb-raider',
        'name' => 'TOMB RAIDER',
        'image' => 'https://i.postimg.cc/7LL4xs6Z/IMG-20251217-214416-779.jpg',
        'category' => 'android',
        'size' => '22.9 GB',
        'description' => 'Penya ndani ya mapango ya kale yaliyofichwa ukiwa kama Lara Croft, ukikutana na mafumbo na hatari',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://buzzheavier.com/65fwvxizlizs'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'winlatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi/releases?fbclid=IwdGRjcAOefzhjbGNrA55_L2V4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHmbsnHy6QYIWzud3TZ1pJFAGIeffnUeFnkBoKrpKtr5x-6DcLFaz77SU6GEl_aem_C0A9FRfUgp7mbtXwVP6Y0g'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'gta-iv',
        'name' => 'GTA IV',
        'image' => 'https://i.postimg.cc/T2jgGMZx/9d4f73088ab678a17bda42671b2568e6.jpg',
        'category' => 'android',
        'size' => '3.84 GB',
        'description' => 'Kutana na maisha ya mtaa katika jiji la Liberty City, ambapo kila siku ni safari mpya ya kujitafutia riziki. Hapa ndipo unapojua thamani ya urafiki na uhalifu.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/ma4lkoin9e0ip7j/GTA%2BIV%2BRIP%2BBy%2BOptiJuegos.7z/file?fbclid=IwdGRjcAOefupjbGNrA55-4GV4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHtMheUm2PI10nvNEYeBrpzUGaLFQlaU7k88s_QjOtEhj3cqxDPErnH_9lYHY_aem_vlx8H1UhqSweYs8F-Unjcw'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'winlatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi/releases?fbclid=IwdGRjcAOefzhjbGNrA55_L2V4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHmbsnHy6QYIWzud3TZ1pJFAGIeffnUeFnkBoKrpKtr5x-6DcLFaz77SU6GEl_aem_C0A9FRfUgp7mbtXwVP6Y0g'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'saveDataLink' => base64_encode('https://www.mediafire.com/file/9dz5zi47jj54ze6/GTA+4+SAVE+DATA.zip/file?fbclid=IwdGRjcAOefyZjbGNrA55_IGV4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHkiJactNnQxd5ylHicmjXeeuBnc948u28itF7In3tQRC1Y4z1GVI_loetpdF_aem_n4TOvouVMuEMiKkRNfD2Eg'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Windows 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'cod-mw3',
        'name' => 'COD MW3',
        'image' => 'https://i.postimg.cc/1tjpz3Q5/wp13629624-call-of-duty-modern-warfare-3-season-2-wallpapers.png',
        'category' => 'pc',
        'size' => '3.52 GB',
        'description' => 'Game hii ni kali sana na ina maudhui ya Kivita mwanzo mwisho hakuna kupoa na kila Misheni vinaibuka vikwazo vipya kiufupi hii game ni kali, Graphics ya Hii game ni 4K',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/ah9krdvotrs1ecg/Call_of_Duty_-_Modern_Warfare_3_%2528Europe%252C_Australia%2529.rvz/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'last-of-us-ii',
        'name' => 'LAST OF US II',
        'image' => 'https://i.postimg.cc/zvXkygsm/the-last-of-us-2-3840x2160-17336.jpg',
        'category' => 'cloud',
        'size' => 'Null',
        'description' => 'Kutana na Joel akipambana na Majeshi ya Serikali kumlinda mtoto wake ambaye Damu yake ni Kinga ya Pandemic disease ambayo imeshamaliza idadi ya watu wengi..je Joel ataweza Kumlinda mtoto wake dhidi ya viumbe wa ajabu na Wanajeshi?',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '8GB+',
        'requirements' => ['Android 10+', 'RAM 4GB+']
    ],
    [
        'id' => 'gta-san-andreas',
        'name' => 'GTA SAN ANDREAS',
        'image' => 'https://i.postimg.cc/MTTDLQWZ/Picsart-25-12-17-17-44-40-709.jpg',
        'category' => 'android',
        'size' => '2.5 GB',
        'description' => 'kitana na CJ, katika ulimwengu wa mitaa na Gang za wahuni. Hapa ndipo unapojifunza sheria za mtaa na kujenga jina lako.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://gta-san-andreas.latestmodapks.com/'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '2GB+',
        'requirements' => ['Windows 7+', 'RAM 2GB+']
    ],
    [
        'id' => 'winds-meet',
        'name' => 'WINDS MEET',
        'image' => 'https://i.postimg.cc/ZR9LmhtM/Picsart-25-12-19-13-14-32-260.jpg',
        'category' => 'android',
        'size' => '1.68 GB',
        'description' => 'Kutana na dada anaitwa Cintra ambae anapewa Mission kutokomeza Uhalifu na Uovu katika Temple za Wajapani ambapo Panga na Bunduki zinalia mwanzo mwisho hakuna kupoa na kila Misheni vinaibuka vikwazo vipya kiufupi hii game ni kali, Graphics ya Hii game ni 4K',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/sm562lgp19jfzpc/base%25282%2529.7z/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => 'Any',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'last-of-us',
        'name' => 'LAST OF US',
        'image' => 'https://i.postimg.cc/jdvS6JGK/IMG-20251217-213632-071.jpg',
        'category' => 'cloud',
        'size' => 'Cloud game',
        'description' => 'Shinda katika ulimwengu uliovamiwa na maambukizi, ukijenga mahusiano na kupigania maisha yako. Hapa kila uamuzi una uzito wa maisha yako.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => 'Any',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'god-of-war',
        'name' => 'GOD OF WAR I',
        'image' => 'https://i.postimg.cc/QdNZhxdj/3389027.jpg',
        'category' => 'android',
        'size' => '7.94 GB',
        'description' => 'Pambana na miungu na viumbe vya kitambo, ukichukua nguvu kutoka kwa maadui wako. Hapa hata majitu huinama mbele yako!',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/c94la9z9wxegvla/God%2Bof%2BWar%2B1%2BVers%C3%A3o%2BIA.iso/file?fbclid=IwdGRjcAOcrIRjbGNrA5yseGV4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHguZ8gvWgyzEQg4yqVbB58EtIle1PXaIJSd2cfUIyhh6d8OBXtRg5ZvotOoc_aem_H4o1R-PBT6M4adUvUQ0WBA'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://aethersx2.net/download-aethersx2-for-android/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'god-of-war-ii',
        'name' => 'GOD OF WAR II',
        'image' => 'https://i.supaimg.com/0be2927a-4a46-4d59-a842-7744972082e1.jpg',
        'category' => 'android',
        'size' => '6.8 GB',
        'description' => 'Endelea safari yako ya kisasi, ukipambana na maadui wakubwa zaidi na kuvunja milango ya mbinguni. Hapa hata miungu huogopa nguvu zako.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://romsfun.com/roms/playstation-2/god-of-war-ii.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://aethersx2.net/download-aethersx2-for-android/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'god-of-war-iii',
        'name' => 'GOD OF WAR III',
        'image' => 'https://i.supaimg.com/b066baf6-e6ac-45ce-a483-5cc04ead9217.jpg',
        'category' => 'cloud',
        'size' => '39.4 GB',
        'description' => 'Jishinde katika mji mzima wa Los Santos bila kuhangaika na kushusha faili. Hapa furaha yako iko kwenye wingu, tayari kukubali!',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://romsfun.com/roms/playstation-3/god-of-war-iii-42825.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/RPCSX/rpcsx-ui-android/releases/tag/v20250425'),
        'graphicsLink' => base64_encode('https://github.com/K11MCH1/AdrenoToolsDrivers/releases'),
        'firmwareLink' => base64_encode('https://www.techspot.com/drivers/driver/file/information/17026/'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => 'Any',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'gta-v-cloud',
        'name' => 'GTA V CLOUD',
        'image' => 'https://i.postimg.cc/LXvgnsMs/Picsart-25-12-17-02-13-37-058.jpg',
        'category' => 'cloud',
        'size' => 'Cloud',
        'description' => 'Jishinde katika mji mzima wa Los Santos bila kuhangaika na kushusha faili. Hapa furaha yako iko kwenye wingu, tayari kukubali!',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('#'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => 'Any',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'watch-dogs',
        'name' => 'WATCH DOGS',
        'image' => 'https://i.postimg.cc/DypvmcFc/Picsart-25-12-19-19-28-15-267.jpg',
        'category' => 'android',
        'size' => '10.3 GB',
        'description' => 'Hii game ni kali sana na pia kama wewe unapenda Maudhui ya Tech hapa ndio kwenyewe mamen,hawa jamaa ni wanahack kila kitu kilichopo mbele yao',
        'keyLink' => base64_encode('https://prodkeys.net/cemu-keys/'),
        'gameLink' => base64_encode('https://romspure.cc/roms/nintendo-wii-u/watch-dogs/'),
        'cemuLink' => base64_encode('https://cemu.en.uptodown.com/android'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'red-dead-redemption',
        'name' => 'RED D REDEMPTION',
        'image' => 'https://i.postimg.cc/4dFmfRwg/IMG-20251217-213320-872.jpg',
        'category' => 'android',
        'size' => '6.26 GB',
        'description' => 'Panda farasi wako na tembea katika nyanda za magharibi, ukikabiliana na wahalifu na wanyama pori. Hapa kila Mission kuna Vikwazo vipya pia Game hii ina Quality kali sana.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/oyvqrgfikuirhb9/Red_Dead_Redemption_NETFLIX_v1.50.60293175_Unlocked_lore.apks/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '8GB+',
        'requirements' => ['Android 11+', 'RAM 8GB+']
    ],
    [
        'id' => 'watch-dogs-ii',
        'name' => 'WATCH DOGS II',
        'image' => 'https://i.postimg.cc/C104GkVw/Picsart-25-12-17-21-31-05-747.jpg',
        'category' => 'android',
        'size' => '24 GB',
        'description' => 'Hii game ni kali sana na pia kama wewe unapenda Maudhui ya Tech hapa ndio kwenyewe mamen,hawa jamaa ni wanahack kila kitu kilichopo mbele yao',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://repack-games.com/watch-dogs-complete-edition-free-download-vi300/#'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi/releases'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 11+', 'RAM 6GB+']
    ],
    [
        'id' => 'mortal-kombat',
        'name' => 'MORTAL KOMBAT CLOUD',
        'image' => 'https://i.postimg.cc/Vs3HKstw/462514-3000x1688-desktop-hd-scorpion-mortal-kombat-wallpapers.jpg',
        'category' => 'cloud',
        'size' => 'cloud game',
        'description' => 'Pigana hadi mwisho na kumaliza maadui wako kwa mikono mitupu, na kila mpinzani ana uwezo wake.Hapa hata kutoka damu ni sehemu ya mchezo!',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode(''),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'uncharted-4',
        'name' => 'UNCHARTED 4',
        'image' => 'https://i.postimg.cc/rFRn6vLj/40632.jpg',
        'category' => 'android',
        'size' => 'cloud game',
        'description' => 'Fuata ramani ya siri na kufikia visiwa vilivyofichwa, ukishindana na maadui ambao wako na wengine wakitumia nguvu kubwa kukuzuia Hapa lazima ujifunze kuwa Survival',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'warfame',
        'name' => 'WARFAME',
        'image' => 'https://i.postimg.cc/sDMhxJvp/Picsart-25-12-19-14-18-32-813.jpg',
        'category' => 'android',
        'size' => '3.0 GB',
        'description' => 'Hapa wewe ni Ninja ila Huna Nguvu za Kiwango cha Juu ila unakumbana na amaadui wenye Skills za hali ya juu na wanaubonda sana,kila hatua unazidi kuwa Bora kuliko wao.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/glnl33gsp2042gs/Warframe_Mobile_%25289_Dic%2529.apks/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 10+', 'RAM 4GB+']
    ],
    [
        'id' => 'mortal-kombat-11',
        'name' => 'MORTAL KOMBAT 11',
        'image' => 'https://i.postimg.cc/L4PdSJSM/Picsart-25-12-19-14-27-06-674.jpg',
        'category' => 'android',
        'size' => '7.44 GB',
        'description' => 'Pigana hadi mwisho na kumaliza maadui wako kwa mikono mitupu, na kila mpinzani ana uwezo wake.Hapa hata kutoka damu ni sehemu ya mchezo!',
        'keyLink' => base64_encode('https://prodkeys.net/yuzu-prod-keys-n25/'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/mxri4xk4w8jg5ja/Mortal+Kombat+11+(USA,+Europe)+(En,Fr,De,Es,It,Pt).xci/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'driversLink' => base64_encode('https://github.com/K11MCH1/AdrenoToolsDrivers/releases/'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('https://github.com/THZoria/NX_Firmware/releases'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '6GB+',
        'requirements' => ['Android 11+', 'RAM 6GB+']
    ],
    [
        'id' => 'life-is-strange',
        'name' => 'LIFE IS STRANGE',
        'image' => 'https://i.postimg.cc/Fz9vBv65/Picsart-25-12-19-15-08-24-123.jpg',
        'category' => 'android',
        'size' => 'null',
        'description' => 'Game hii ni kali sana na ina story mode nzuri na ina Graphics kali sana, kila Mission vinaibuka vikwazo vipya kiufupi hii game ni kali',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://apkaward.com/life-is-strange'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '3GB+',
        'requirements' => ['Android 8+', 'RAM 3GB+']
    ],
    [
        'id' => 'bully',
        'name' => 'BULLY',
        'image' => 'https://i.postimg.cc/JnS6s5bc/Picsart-25-12-19-15-13-28-237.jpg',
        'category' => 'android',
        'size' => '2.2 GB',
        'description' => 'Hapa utaishi maisha ya Ubabe ya Shuleni huku ukikumbana na vikwazo vya wazazi na walimu kila mara, yani kiufupi unakuwa mbabe kwa wanafunzi na Walimu',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/hphe263g9meclue/Bully-v1.4.299-60FPS-full-apkvision.apk/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '3GB+',
        'requirements' => ['Android 7+', 'RAM 3GB+']
    ],
    [
        'id' => 'little-nightmare',
        'name' => 'LITTLE NIGHTMARE I',
        'image' => 'https://i.postimg.cc/9Mf5dbwm/file-000000005b8071f896e71d3d0596605b.png',
        'category' => 'android',
        'size' => '1.50 GB',
        'description' => 'Kimbia kutoka kwenye ndoto za kutisha, ukijaribu kupata njia ya kutoka katika ulimwengu wa hofu. Hapa hata kivuli chako kinaweza kukudhuru.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/25qac2mpnrzx23g/little-nightmaressss_144-.apk/file'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'little-nightmare2',
        'name' => 'LITTLE NIGHTMARE II',
        'image' => 'https://i.postimg.cc/9Mf5dbwm/file-000000005b8071f896e71d3d0596605b.png',
        'category' => 'android',
        'size' => '3.10 GB',
        'description' => 'Kimbia kutoka kwenye ndoto za kutisha, ukijaribu kupata njia ya kutoka katika ulimwengu wa hofu. Hapa hata kivuli chako kinaweza kukudhuru.',
        'keyLink' => base64_encode('https://prodkeys.net/yuzu-prod-keys-n25/'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/gxcwneucw6hom6p/Little_Nightmares_Complete_Edition.nsp/file'),
        'yuzuLink' => base64_encode('https://yuzuemulators.com/'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'driversLink' => base64_encode('https://yuzuemulator.org/gpu-drivers/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('https://github.com/THZoria/NX_Firmware/releases'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'god-hand',
        'name' => 'GOD HAND',
        'image' => 'https://i.postimg.cc/ryCZVxDN/Picsart-25-12-19-15-28-02-938.jpg',
        'category' => 'android',
        'size' => '4.5 GB',
        'description' => 'Piga maadui wako kwa kasi ya umeme, ukijenga mchanganyiko wa vibao vya kuvunja mifupa. Hapa Siraha kubwa ni Skills za Kupigana ulizonazo na mkono wako! wenye Nguvu za Ajabu',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://romsfun.com/roms/playstation-2/god-hand.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://aethersx2.net/download-aethersx2-for-android/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '2GB+',
        'requirements' => ['Android 7+', 'RAM 2GB+']
    ],
    [
        'id' => 'downhill',
        'name' => 'DOWNHILL',
        'image' => 'https://i.postimg.cc/c13Cr7YD/Picsart-25-12-19-15-58-39-551.jpg',
        'category' => 'android',
        'size' => '1.2 GB',
        'description' => 'Panda baiskeli yako na kuteremka mlima kwa kasi ya Katarama & kimbunga, ukiepuka vikwazo vyote,atumia njia zote ili ushinde kila round ukishindana na wapinzani wenye uwezo mkubwa wa kukimbiza baiskeli kwa kasi ya sgr',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://romsfun.com/roms/playstation-2/downhill-domination.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://aethersx2.net/download-aethersx2-for-android/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '2GB+',
        'requirements' => ['Android 7+', 'RAM 2GB+']
    ],
    [
        'id' => 'jade-empire',
        'name' => 'JADE EMPIRE',
        'image' => 'https://i.postimg.cc/yNSxc05M/Picsart-25-12-19-16-08-18-545.jpg',
        'category' => 'android',
        'size' => '3.0 GB',
        'description' => 'Jifunze sanaa za vita za kale, ukishindana na vikwazo kuweza kujenga hadithi yako ya kifalme.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/nj0o0eksdrmtkkm/JadeEmpire_1.0.0_MOD_HF3_sign.apk/file?fbclid=IwdGRjcAORv81jbGNrA5G_x2V4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHtP9BX1dNeDXOoeC4lfk7ma3F2IGtH22g6VJLKQLHeEPreTTx-ppvrH6KAnA_aem_QQDnWHqVshfgId_Jpedhfw'),
        'yuzuLink' => base64_encode('#'),
        'obbLink' => base64_encode('https://www.mediafire.com/file/nre0u47x83a8hfg/techj5gamesjeseobb.rar/file?fbclid=IwdGRjcAORv-9jbGNrA5G_6mV4dG4DYWVtAjExAHNydGMGYXBwX2lkDDM1MDY4NTUzMTcyOAABHiALuXTf12Agx9udtUdWcnPy5N7ofXFL0DBzhIQ1spbpY_IJSgn8Iwd5Rsjc_aem_HXhUkMzj0UE9Biegqr8ePw'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '3GB+',
        'requirements' => ['Android 8+', 'RAM 3GB+']
    ],
    [
        'id' => 'pascal-wager',
        'name' => 'PASCAL WAGER',
        'image' => 'https://i.postimg.cc/tCkGv7Wn/Picsart-25-12-19-16-22-05-189.jpg',
        'category' => 'android',
        'size' => '2.5 GB',
        'description' => 'Pigana na viumbe vya giza katika ulimwengu uliojaa mafumbo, ukijaribu kupata ukweli wa mazingira yako. Hapa kila kivuli kina siri yake ya kutisha.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://5play.org/en/11915-pascals-wager.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'bus-simulator',
        'name' => 'BUS SIMULATOR VIP',
        'image' => 'https://i.postimg.cc/CLFZRTrj/IMG-20251221-WA0044.jpg',
        'category' => 'android',
        'size' => '3.5 GB',
        'description' => 'Endesha basi yako Ukiwa kama Dereva wa Mabasi ya mkoa,game hii ni kali sana na ina Ramani ya Barabara za Tanzania huku ukipishana na mabasi ya kampuni za Tanzania, Shindana na Madereva wenzako kukimbizana njiani kufikisha abiria Terminal',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode(''),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'jetli',
        'name' => 'JET LI:RISE TO HONOR',
        'image' => 'https://i.postimg.cc/hjXGLKWd/Picsart-25-12-22-01-03-42-857.jpg',
        'category' => 'android',
        'size' => '2.5 GB',
        'description' => 'Jikumbatie sanaa za kungfu na kupambana na wahalifu, ukijenga hadithi yako ya ushujaa. Hapa kila ngumi ni hatua kuelekea heshima.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.igpsp'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'san-andrea',
        'name' => 'GTA SAN ANDREAS CLOUD',
        'image' => 'https://i.postimg.cc/BQ4BCzbn/Picsart-25-12-22-01-26-10-099.jpg',
        'category' => 'cloud',
        'size' => 'cloud game',
        'description' => 'Furahia ulimwengu wa mitaa wa San Andreas huku ukizungukwa na magenge ya Wahuni na kukabiriana nao, huku ukicheza mission mbalimbali na vikwazo vingi ukiwa kama CJ',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode(''),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'fcgame',
        'name' => 'FC 26',
        'image' => 'https://i.postimg.cc/MK71MmYx/22537635.jpg',
        'category' => 'android',
        'size' => '13.5 GB',
        'description' => 'Game hii ni kali sana na ina graphics za kiwango cha juu, Cheza Mpira kwenye Peach za kali bila kiwa na data..kila kitu Offline!',
        'keyLink' => base64_encode('https://prodkeys.net/yuzu-prod-keys-n25/'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/gaizuarpykzoew8/EA_SPORTS_FIFA_23_Nintendo_Switch_Legacy_Edition_%255B01001C8016B4E000%255D%255Bv0%255D.nsp/file'),
        'obbLink' => base64_encode('https://www.mediafire.com/file/fzqsguvcs3ilfb6/FIFA22+MOD+FC26.zip/file'),
        'yuzuLink' => base64_encode('https://yuzuemulators.com/'),
        'gamehubLink' => base64_encode('#'),
        'driversLink' => base64_encode('https://yuzuemulator.org/gpu-drivers/'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('https://vimeo.com/1148364299?share=copy&fl=sv&fe=ci'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 12+', 'RAM 8GB+']
    ],
    [
        'id' => 'vicecity',
        'name' => 'Gta Vice City',
        'image' => 'https://i.postimg.cc/SQDJw1VN/Picsart-25-12-22-01-29-42-297.jpg',
        'category' => 'cloud',
        'size' => 'cloud game',
        'description' => 'Rudi kwenye jiji la Vice City lenye rangi kali na muziki mzuri, ukijenga utawala wako wa kihalifu. Hapa kila usiku una mwamko mpya.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'cyberpunk',
        'name' => 'CYBERPUNK',
        'image' => 'https://i.postimg.cc/0ymmRdzq/wp6736126-cyberpunk-4k-wallpapers.jpg',
        'category' => 'cloud',
        'size' => 'cloud game',
        'description' => 'Zama katika jiji la baadaye lenye teknolojia ya hali ya juu, ukichagua njia yako ya kijeshi au mwonekano. Hapa kila chaguo linaweza kubadilisha hatima yako.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'darksouls',
        'name' => 'DARK SOULS',
        'image' => 'https://i.postimg.cc/5N4ktyBc/Dark-Souls-Game-Warrior-4k-Wallpaper-In-High-Quality.jpg',
        'category' => 'android',
        'size' => '4.5 GB',
        'description' => 'Pambana na viumbe vya giza na kubeba mzigo wa hatima yako, ukijaribu kupata mwanga katika ulimwengu wa giza. Hapa kila kufa ni somo jipya.',
        'keyLink' => base64_encode('https://prodkeys.net/yuzu-prod-keys-n25/'),
        'gameLink' => base64_encode('https://buffdrive.com/398'),
        'yuzuLink' => base64_encode('https://yuzuemulators.com/'),
        'driversLink' => base64_encode('https://github.com/K11MCH1/AdrenoToolsDrivers/releases/'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('https://github.com/THZoria/NX_Firmware/releases'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 10+', 'RAM 4GB+']
    ],
    [
        'id' => 'silent',
        'name' => 'SILENT HILL',
        'image' => 'https://i.postimg.cc/jj1LDDw1/Picsart-25-12-22-01-46-51-224.jpg',
        'category' => 'android',
        'size' => '2.5 GB',
        'description' => 'Ingia ndani ya mji wa hofu na kutafuta ukweli wa siri zake, ukikabiliana na maovu yasiyoelezeka. Hapa ukimya unaopatikana kwenye game hii ni wa kutisha.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://romsfun.com/roms/nintendo-wii/silent-hill-shattered-memories-2.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://play.google.com/store/apps/details?id=org.dolphinemu.dolphinemu'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'fifa23',
        'name' => 'FIFA 23',
        'image' => 'https://i.postimg.cc/Bn6Qq3SV/Picsart-25-12-22-02-02-01-242.jpg',
        'category' => 'android',
        'size' => '3.5 GB',
        'description' => 'Sasa unaweza Kucheza Fifa23 kwenye Simu yako bila shida ukifurahia modes zote Free no Coins na Game hii ni Offline fifa 2023',
        'keyLink' => base64_encode('https://prodkeys.net/yuzu-prod-keys-n25/'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/gaizuarpykzoew8/EA_SPORTS_FIFA_23_Nintendo_Switch_Legacy_Edition_%255B01001C8016B4E000%255D%255Bv0%255D.nsp/file'),
        'yuzuLink' => base64_encode('https://yuzuemulators.com/'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'resident',
        'name' => 'RESIDENT EVIL II',
        'image' => 'https://i.postimg.cc/Bb4PpzTK/wp3815686-resident-evil-2-remake-wallpapers.jpg',
        'category' => 'android',
        'size' => '3.5 GB',
        'description' => 'Jiokoe kutoka kwenye jiji lililovamiwa na maambukizi, ukijaribu kupata njia ya kutoka na kuvunja siri za hatari. Graphics za hili game ni kali sana HD.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=org.dolphinemu.dolphinemu'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://play.google.com/store/apps/details?id=org.dolphinemu.dolphinemu'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'ninja',
        'name' => 'NINJA GAIDEN',
        'image' => 'https://i.postimg.cc/nLxxXtZ6/Picsart-25-12-22-02-20-19-675.jpg',
        'category' => 'android',
        'size' => '3.5 GB',
        'description' => 'Hapa wewe ni Ninja na unakumbana na amaadui wenye Skills za hali ya juu na wanaubonda sana,kila hatua unazidi kuwa Bora kuliko wao.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode(''),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'residenteviil',
        'name' => 'RESIDENT EVIL 4',
        'image' => 'https://i.postimg.cc/qB12Qk55/Picsart-25-12-22-02-30-43-106.jpg',
        'category' => 'android',
        'size' => '4.5 GB',
        'description' => 'Peleka misheni ya kuokoa katika kijiji cha hatari, ukikabiliana na viumbe vya kutisha na kuvunja mfumo wa uovu. Hapa kila risasi ina thamani yake.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://romsfun.com/roms/nintendo-wii/resident-evil-4-wii-edition.html'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://play.google.com/store/apps/details?id=org.dolphinemu.dolphinemu'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 12+', 'RAM 6GB+']
    ],
    [
        'id' => 'residentevil',
        'name' => 'RESIDENT EVIL 3',
        'image' => 'https://i.postimg.cc/mgmxg1Xw/wp12116675-resident-evil-4-remake-wallpapers.png',
        'category' => 'cloud',
        'size' => 'cloud game',
        'description' => 'Endelea na misheni yako ya kuokoa katika ulimwengu uliojaa hatari, ukijaribu kupata dawa ya maambukizi. Hapa kila kona inaficha hatari mpya.',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 10+', 'RAM 6GB+']
    ],
    [
        'id' => 'sniperelite',
        'name' => 'SNIPER ELITE 4',
        'image' => 'https://i.postimg.cc/WzNCV2GC/Picsart-25-12-22-02-44-26-438.jpg',
        'category' => 'android',
        'size' => '6.5 GB',
        'description' => 'Hapa wewe ni Mwanajeshi kitengo cha Sniper Sharp Shooter unashoot maadui wako kwa umbali mrefu ukijaribu kukamilisha misheni yako ya kijeshi. maadui watakuita jina "ghost" sababu hujawahi kukosea ni mwendo wa za kichwa tu',
        'keyLink' => base64_encode('https://prodkeys.net/yuzu-prod-keys-n25/'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/53403ces3vtlujd/Sniper_Elite_4_%255B010007B010FCC000%255D%255Bv0%255D.nsp.rar/file'),
        'driversLink' => base64_encode('https://yuzuemulator.org/gpu-drivers/'),
        'yuzuLink' => base64_encode('https://yuzuemulators.com/'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('https://github.com/THZoria/NX_Firmware/releases'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'jistcause4',
        'name' => 'JUSTCAUSE 4',
        'image' => 'https://i.postimg.cc/zfMT5pnm/Picsart-25-12-22-02-54-43-766.jpg',
        'category' => 'android',
        'size' => 'cloud game',
        'description' => 'Hii game ina graphics kali sana pia imejaa mkono mwanzo mwisho hakuna kupoa..mzee wa kuruka juu ya helicopter bila parachute',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://play.google.com/store/apps/details?id=com.cga.cloudgame.platform'),
        'yuzuLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'sifu',
        'name' => 'SIFU',
        'image' => 'https://i.postimg.cc/66hTfYyQ/Picsart-25-12-22-02-59-36-521.jpg',
        'category' => 'android',
        'size' => '7.5 GB',
        'description' => 'Jifunze sanaa za kungfu na kupambana na maadui, ukijaribu kupata haki kwa mikono yako mwenyewe.',
        'keyLink' => base64_encode('https://prodkeys.net/yuzu-prod-keys-n25/'),
        'gameLink' => base64_encode('https://www.mediafire.com/file_premium/5zqc8z4o79410uc/Sifu_2.xci/file'),
        'yuzuLink' => base64_encode('https://yuzuemulators.com/'),
        'driversLink' => base64_encode('https://github.com/K11MCH1/AdrenoToolsDrivers/releases/'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('https://github.com/THZoria/NX_Firmware/releases'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'combatzone',
        'name' => 'COMBAT ZONE',
        'image' => 'https://i.supaimg.com/0806c762-d79d-4f22-9b69-c94447e11ea0.jpg',
        'category' => 'android',
        'size' => '3.5 GB',
        'description' => 'Hapa ukiwa mwanajeshi unapokea Mission ya kwenda kutumikia taifa lako ukiwa na wenzako mnakiwasha kuteketeza adui waliokuwa mbele yenu.',
        'keyLink' => base64_encode('https://prodkeys.net/yuzu-prod-keys-n25/'),
        'gameLink' => base64_encode('https://buzzheavier.com/5l5mojiwiuj6'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('https://github.com/K11MCH1/AdrenoToolsDrivers/releases/'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('https://citron-emu.org/'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('https://github.com/THZoria/NX_Firmware/releases'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'ninjacreed',
        'name' => 'NINJA CREED',
        'image' => 'https://i.supaimg.com/262b5935-df3d-4d3d-a5e2-398b978b3c83.jpg',
        'category' => 'android',
        'size' => '2.5 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://5play.org/en/12283-ninjas-creed-3d-sniper-shooting-assassin-game.html'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'moderncombat',
        'name' => 'MODERN COMBAT 4',
        'image' => 'https://i.supaimg.com/7db9d00e-da19-4340-add5-8b1f76a9d28b.jpg',
        'category' => 'android',
        'size' => '2.3 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://5play.org/en/118-modern-combat-4-zero-hour.html'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'realboxing',
        'name' => 'REAL BOXING II',
        'image' => 'https://i.supaimg.com/0d3da7a0-3631-4ee5-83aa-7de03da39a1b.jpg',
        'category' => 'android',
        'size' => 'null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://5play.org/index.php?do=cdn&id=168991&lang=en'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'deadspace',
        'name' => 'DEAD SPACE',
        'image' => 'https://i.supaimg.com/2a1697bd-4cd0-4479-92d8-7f930ebbfdec.jpg',
        'category' => 'android',
        'size' => '8.5 GB',
        'description' => 'Tumia Winlator 10Hotfix',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://repack-games.com/dead-space-free-download-vi54/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/brunodev85/winlator/releases'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'deadpool',
        'name' => 'DEADPOOL',
        'image' => 'https://i.supaimg.com/427f7252-e89c-43b9-89c7-9747032c68c0.jpg',
        'category' => 'android',
        'size' => 'null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://gamingbeasts.com/deadpool-the-game-free-pc-game/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://devuploads.com/m3v49caa0fv2'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'gtaiv',
        'name' => 'GTA IV LITE',
        'image' => 'https://i.supaimg.com/68c53cd0-9462-4a1d-a34a-5f19a76bfa04.jpg',
        'category' => 'android',
        'size' => '4.3 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.mediafire.com/file/tll8jgxjbgizsp4/GTA_IV_High_Compress.zip/file'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('http://github.com/REF4IK/Wiinlator-Ref4ik-'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'resedentevil6',
        'name' => 'RESIDENT EVIL VI',
        'image' => 'https://i.supaimg.com/3d1991b8-7b02-47be-af93-2cef0eaf911a.jpg',
        'category' => 'android',
        'size' => '10.5 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://nswpedia.com/download/resident-evil-6-86-10223'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('https://github.com/eden-emulator/Releases/releases'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('https://prodkeys.net/yuzu-firmware-v3/'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'xmen',
        'name' => 'X-MEN',
        'image' => 'https://i.supaimg.com/9636b0d0-7109-4f12-afc1-cae758b240d1.jpg',
        'category' => 'android',
        'size' => '5.9 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://datanodes.to/v0ncr8vrvxuv/X-Men-Origins-Wolverine-.rar'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'wwepro',
        'name' => 'WWE 2K19',
        'image' => 'https://i.supaimg.com/58cc3b65-6281-419d-916c-c6a664d54d4a.jpg',
        'category' => 'android',
        'size' => '45 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://steamrip.com/wwe-2k19-free-download-d5/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://gamehub.xiaoji.com/'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'mafiaii',
        'name' => 'MAFIA II',
        'image' => 'https://i.supaimg.com/10738cf2-e05f-4e87-8728-673015830a14.jpg',
        'category' => 'android',
        'size' => '11 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://gofile.io/d/V8Juy0'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi/releases'),
        'graphicsLink' => base64_encode('https://www.mediafire.com/file/vwso1rax5tgcnt5/PhysX-9.19.0218-SystemSoftware.exe/file'),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('https://youtu.be/dWBl-4YbgN8'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'sleepingdogs',
        'name' => 'SLEEPING DOGS',
        'image' => 'https://i.supaimg.com/85b34209-2f04-4ed5-b6a7-2a3524a4c97c.jpg',
        'category' => 'android',
        'size' => 'null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://repack-games.com/sleeping-dogs-definitive-edition-free-download-v/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi/releases'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'gtavpc',
        'name' => 'GTA 5 PC',
        'image' => 'https://i.supaimg.com/580a60fa-eb05-42fd-a909-a3244b3b74cf.jpg',
        'category' => 'pc',
        'size' => 'null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://gamingbeasts.com/34-grand-theft-auto-5-pc-download-full-game-77/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'codblackops',
        'name' => 'COD BLACK OPS',
        'image' => 'https://i.supaimg.com/cc7130b4-7191-49e3-ae89-ef326ae7fbe0.jpg',
        'category' => 'pc',
        'size' => 'null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://gamingbeasts.com/2-call-of-duty-black-ops-download-for-free/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('https://github.com/K11MCH1/AdrenoToolsDrivers/releases'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('https://youtu.be/dqXlrOIXzSI'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'godofwapc',
        'name' => 'GOD OF WAR PC',
        'image' => 'https://i.supaimg.com/b2dea84d-3de8-4c42-ab68-cb7e0a226b52.jpg',
        'category' => 'pc',
        'size' => 'Null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://steamrip.com/god-of-as2wxy-26w/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://gamehub.xiaoji.com/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('https://youtu.be/z-7MQ0FsZeE'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'tombraiderpc',
        'name' => 'TOMB RAIDER PC',
        'image' => 'https://i.supaimg.com/5faf26fc-ec5d-405a-8a6c-cfed18d3b0c6.jpg',
        'category' => 'pc',
        'size' => '20.5 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://gamingbeasts.com/tomb-raider-download-full-game-pc/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://github.com/Succubussix/winlator-bionic-glibc/releases'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'farcryy4',
        'name' => 'FAR CRY 4',
        'image' => 'https://i.supaimg.com/2835ecce-26d2-45e9-b39d-724c51fabb6f.jpg',
        'category' => 'android',
        'size' => '27 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://repack-games.com/far-cry-4-gold-edition-free-download-vi157/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('http://github.com/coffincolors/winlator/releases/tag/cmod_v13.1'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'motogp',
        'name' => 'motoGP 17',
        'image' => 'https://i.supaimg.com/d1f53a57-aee5-43f5-8118-3b126a604db9.jpg',
        'category' => 'android',
        'size' => 'null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://repack-games.com/motogp-17-free-download-vi12/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('https://github.com/zzappvn/Visual-C-Redistributable-Runtimes-All-in-One/releases/tag/14.38.33135.0'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/StevenMXZ/Winlator-Ludashi/releases'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'farcry1',
        'name' => 'FAR CRY 1',
        'image' => 'https://i.supaimg.com/6c7f4558-b299-4630-9a1e-44ce4a655c8e.jpg',
        'category' => 'android',
        'size' => '2.5 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://peskgames.com/en/pc-games/far-cry-1'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://gamehub.xiaoji.com/'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'farcry3a',
        'name' => 'FAR CRY 3 LITE',
        'image' => 'https://i.supaimg.com/2835ecce-26d2-45e9-b39d-724c51fabb6f.jpg',
        'category' => 'android',
        'size' => '5.2 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://peskgames.com/en/pc-games/far-cry-3-digital-deluxe-edition-blood-dragon'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://gamehub.xiaoji.com/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'farcry5',
        'name' => 'FAR CRY 5',
        'image' => 'https://i.supaimg.com/75cf2f18-cc4f-44e4-a2de-c070faff2634.jpg',
        'category' => 'pc',
        'size' => '53.6 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://peskgames.com/en/pc-games/far-cry-5'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://gamehub.xiaoji.com/'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'hitman3',
        'name' => 'HITMAN 3',
        'image' => 'https://i.supaimg.com/b908a438-36a6-435c-8774-42536b60f989.jpg',
        'category' => 'pc',
        'size' => '41 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://peskgames.com/en/pc-games/hitman-3'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://gamehub.xiaoji.com/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'combatzon4e',
        'name' => 'SOON...',
        'image' => 'https://i.postimg.cc/Qtv3nyJk/b0f3b25cf6411385180fc70d6d54d9d8.jpg',
        'category' => 'android',
        'size' => 'null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('#'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'detroithuman',
        'name' => 'DETROIT B HUMAN',
        'image' => 'https://i.supaimg.com/e524c14e-54fd-4d5d-9c02-e37fcb5d72e9.jpg',
        'category' => 'android',
        'size' => 'null',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://peskgames.com/en/pc-games/detroit-become-human'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('https://gamehub.xiaoji.com/'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode(''),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'asassincreedpcg',
        'name' => 'ASSASSIN CREED PC',
        'image' => 'https://i.supaimg.com/6d0ac7f1-2b89-4b0b-9508-561718a28030.jpg',
        'category' => 'android',
        'size' => '20.3 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://peskgames.com/en/pc-games/assassins-creed-mirage-master-assassin-edition'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://gamehub.xiaoji.com/'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ],
    [
        'id' => 'assaincreed2',
        'name' => 'ASSASSIN CREED IV ',
        'image' => 'https://i.supaimg.com/59ebadb1-a5fc-4c7c-b3da-193f77ec9014.jpg',
        'category' => 'android',
        'size' => '6.5 GB',
        'description' => 'Hii game inasupport PC na kwa simu za Android tumia Emulator ili kucheza kwenye Simu au fungua exe file kucheza kwenye PC',
        'keyLink' => base64_encode('#'),
        'gameLink' => base64_encode('https://www.arealgamer.org/assassins-creed-4-black-flag-pc/'),
        'yuzuLink' => base64_encode('#'),
        'driversLink' => base64_encode('#'),
        'gamehubLink' => base64_encode('#'),
        'edenLink' => base64_encode('#'),
        'citronLink' => base64_encode('#'),
        'emulatorLink' => base64_encode('https://github.com/brunodev85/winlator'),
        'graphicsLink' => base64_encode(''),
        'firmwareLink' => base64_encode('#'),
        'videoLink' => base64_encode('#'),
        'version' => 'null',
        'ram' => '4GB+',
        'requirements' => ['Android 9+', 'RAM 4GB+']
    ]
];

// ================= SEND RESPONSE =================
header('Content-Type: application/json');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Cache-Control: post-check=0, pre-check=0', false);
header('Pragma: no-cache');

echo json_encode([
    'success' => true,
    'count' => count($gamesData),
    'games' => $gamesData,
    'timestamp' => time()
]);
?>
